name: Quantik CI/CD Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”¹ Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ”¹ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸ”¹ Instalar dependencias
        run: npm install

      - name: ğŸ”¹ Compilar proyecto
        run: npm run build

      - name: ğŸš€ Desplegar en Vercel
        run: |
          npm install -g vercel
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --force
